FROM maven:3.9.5-eclipse-temurin-17

# Install SSH client and minimum required tools
RUN apt-get update && \
    apt-get install -y \
    openssh-client \
    curl \
    ca-certificates \
    gnupg2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Setup SSH directory
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

# Set working directory
WORKDIR /app